### ISSUE TITLE
Error: Could not start the command: 

### ISSUE THREAD

**Issue by ttpro1995** [wakatime/texstudio-wakatime#1]
Error: Could not start the command: wakatime --entity "/home/thaithien/workplace/school/tkcs_k27_momentum_lr_decay/cite.bib" --plugin "texstudio/135176 texstudio-wakatime/1.0.0" --write --lineno 5 --cursorpos 182

**Comment by alanhamlett** [comment]
Probably means you need to install [wakatime-cli](https://github.com/wakatime/wakatime):

`sudo pip install wakatime`

**Comment by ttpro1995** [comment]
I did installed wakatime-cli with 

        pip install wakatime

With anaconda (so no sudo) 

I copy and paste the command

        "/home/thaithien/workplace/school/tkcs_k27_momentum_lr_decay/cite.bib" --plugin "texstudio/135176 texstudio-wakatime/1.0.0" --write --lineno 5 --cursorpos 182

into terminal (zsh). It run without showing any error. 

However, error keep showing in tex studio

**Comment by gandarez** [comment]
You should allow the execution of `wakatime` as below, have you done that?
<img width="682" alt="Screen Shot 2019-07-16 at 11 08 38" src="https://user-images.githubusercontent.com/782854/61301366-20597500-a7ba-11e9-85de-46c7e5c80760.png">

**Comment by alanhamlett** [comment]
> However, error keep showing in tex studio

What's the error message shown?

**Comment by gandarez** [comment]
closing due the lack of response. Feel free to reopen it.

**Comment by tianyilt** [comment]
I directly change the wakatime path in macros script.
Textudio-> Macros->Edit Macros 
Find latex context and edit first args in  line 45.
As for me, it is `'C:\Users\\tianyilt\\.wakatime\\wakatime-cli-windows-amd64.exe'`.

**Comment by Fishezzz** [comment]
On **Linux**, I made it work by editing the TexStudio macro and changing `~/.wakatime/wakatime-cli` to `$HOME/.wakatime/wakatime-cli` in the `args` array.

**Comment by alanhamlett** [comment]
Fixed with 634eb162ee40209675303566330e42954b9a752c.

**Comment by callanwu** [comment]
@tianyilt thx a lot~
