### ISSUE TITLE
TypeError: Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by muety** [wakatime/texstudio-wakatime#5]
When trying to execute `install.py`, I'm getting the following error in line 108.

```
TypeError: Object of type bytes is not JSON serializable
```

**Comment by alanhamlett** [comment]
Which version of Python do you have on your machine?

**Comment by muety** [comment]
I am using 3.7.4. The problem does not occur with Python 2.7. Fix is provided in #6.

**Comment by alanhamlett** [comment]
22333a6cbd47693666cfb42d7fd7804579695e4c improves on #6 by decoding as soon as possible and only for Python3.
