### ISSUE TITLE
Read the response before decoding in python 3

### ISSUE THREAD

**Issue by Koushikphy** [wakatime/texstudio-wakatime#8]
In case of Python 3 don't we have to read the response before decoding it.  
https://github.com/wakatime/texstudio-wakatime/blob/master/install.py#L79-L82  

i.e. it should be 
```python
resp.read().decode('utf-8')
```

**Comment by alanhamlett** [comment]
Fixed with 42c10af76b578320174a8dcf680e67d12c693dbc. Thank you!
